version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: takizawaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./takizawadb_backup.sql:/docker-entrypoint-initdb.d/takizawadb_backup.sql

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: takizawa-django
    command: >
      bash -c "python manage.py migrate &&
               gunicorn takizawa.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
