# Generated by Django 5.1.6 on 2025-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
